version: '3.1'

services:

  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: gpt3
      MONGO_INITDB_ROOT_PASSWORD: gpt3
    ports:
      - "27017:27017"

  bot:
    environment:
      DISCORD_TOKEN: token
      MONGO_DBUSER: gpt3
      MONGO_DBPASS: gpt3
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DBNAME: gpt3
      PREFIX: !
      LOG_LEVEL: DEBUG
