name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
      - name: Set up environment variables
        run: export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --output-file=flake8.out
      - name: Test with pytest
        run: |
          pytest Tests/ApiClientTest.py --doctest-modules --junitxml=junit/test-results.xml
        with:
          name: pytest-reports
          path: junit/test-results.xml
          if-no-files-found: error
          retention-days: 7
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: flake8-report
          path: flake8.out
          if-no-files-found: error
          retention-days: 7